/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import modelo.Cliente;
import controle.ClienteController;
import javax.swing.JFrame;

/**
 *
 * @Josieli
 */
public class ClienteJD extends javax.swing.JDialog {

    private CadastrarOrdemServicoJD ordemServico;

    ArrayList<Cliente> listaClientes = new ArrayList<>();

    public void carregarClientes() {
        DefaultListModel modelo = new DefaultListModel();
        modelo.removeAllElements();

        for (Cliente c : listaClientes) {
            modelo.addElement(c);
        }

        lstClientes.setModel(modelo);
    }

    /**
     * Creates new form ClienteJF
     */
    public ClienteJD(java.awt.Window parent, CadastrarOrdemServicoJD ordemServico, boolean modal) {
        super(parent, ModalityType.APPLICATION_MODAL);
        this.ordemServico = ordemServico;
        initComponents();
        carregarClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstClientes = new javax.swing.JList<>();
        bntAdicionar = new javax.swing.JButton();
        bntRemover = new javax.swing.JButton();
        bntEditar = new javax.swing.JButton();
        bntSelecionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblTitulo.setText("Clientes Cadastrados");

        jScrollPane1.setViewportView(lstClientes);

        bntAdicionar.setText("Adicionar");
        bntAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAdicionarActionPerformed(evt);
            }
        });

        bntRemover.setText("Remover");
        bntRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRemoverActionPerformed(evt);
            }
        });

        bntEditar.setText("Editar");
        bntEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEditarActionPerformed(evt);
            }
        });

        bntSelecionar.setText("Selecionar");
        bntSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSelecionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bntAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                .addComponent(bntRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(bntEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntSelecionar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitulo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(bntAdicionar)
                        .addGap(18, 18, 18)
                        .addComponent(bntRemover)
                        .addGap(18, 18, 18)
                        .addComponent(bntEditar)
                        .addGap(18, 18, 18)
                        .addComponent(bntSelecionar)))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRemoverActionPerformed
        Cliente clienteSelecionado = lstClientes.getSelectedValue();
        if (clienteSelecionado != null) {
            int opRemover = JOptionPane.showConfirmDialog(rootPane, "Tem certeza que deseja remover o cliente? " + clienteSelecionado.getNome());
            if (opRemover == JOptionPane.YES_OPTION) {
                listaClientes.remove(clienteSelecionado);
                carregarClientes();
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um cliente para remover!!");
        }
    }//GEN-LAST:event_bntRemoverActionPerformed

    private void bntAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAdicionarActionPerformed
        CadastrarClienteJD telaCadastrarCliente = new CadastrarClienteJD(this, true);
        telaCadastrarCliente.setVisible(true);

        Cliente clienteNovo = telaCadastrarCliente.getCliente();
        if (clienteNovo != null) {
            ClienteController control = new ClienteController();
            listaClientes = (ArrayList<Cliente>) control.addCliente(clienteNovo, listaClientes);
            carregarClientes();
        }

    }//GEN-LAST:event_bntAdicionarActionPerformed


    private void bntSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSelecionarActionPerformed
        Cliente clienteSelecionado = lstClientes.getSelectedValue();
        if (clienteSelecionado != null) {
            if (ordemServico != null) {
                ordemServico.setCliente(clienteSelecionado);
            }
        } else {
            JOptionPane.showMessageDialog(this, "A tela de Ordem de Serviço não está vinculada!");
        }
        this.dispose();


    }//GEN-LAST:event_bntSelecionarActionPerformed

    private void bntEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEditarActionPerformed
        Cliente clienteSelecionado = lstClientes.getSelectedValue();
        if (clienteSelecionado != null) {

            CadastrarClienteJD telaCadastro = new CadastrarClienteJD(this, true);
            telaCadastro.setCliente(clienteSelecionado);

            telaCadastro.setVisible(true);

            carregarClientes();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um cliente para editar!!");
        }
    }//GEN-LAST:event_bntEditarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ClienteJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ClienteJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ClienteJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ClienteJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ClienteJF().setVisible(true);
//            }
//        });;
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAdicionar;
    private javax.swing.JButton bntEditar;
    private javax.swing.JButton bntRemover;
    private javax.swing.JButton bntSelecionar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JList<Cliente> lstClientes;
    // End of variables declaration//GEN-END:variables
}
