/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import modelo.OrdemServico;
import controle.OrdemServicoController;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import modelo.Cliente;

/**
 *
 * @Josieli
 */
public class OrdemServicoJF extends javax.swing.JFrame {

    ArrayList<OrdemServico> listaOrdemServico = new ArrayList<>();

    public void carregarOrdemServico() {
        DefaultListModel modelo = new DefaultListModel();
        modelo.removeAllElements();

        for (OrdemServico s : listaOrdemServico) {
            modelo.addElement(s);
        }

        lstServicos.setModel(modelo);

    }

    /**
     * Creates new form OrdemServico
     */
    public OrdemServicoJF() {
        initComponents();
        carregarOrdemServico();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstServicos = new javax.swing.JList<>();
        bntAdicionarServico = new javax.swing.JButton();
        bntRemoverServico = new javax.swing.JButton();
        bntEditarServico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 204));
        lblTitulo.setText("Serviços Cadastrados");

        jScrollPane1.setViewportView(lstServicos);

        bntAdicionarServico.setBackground(new java.awt.Color(51, 153, 255));
        bntAdicionarServico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntAdicionarServico.setForeground(new java.awt.Color(255, 255, 255));
        bntAdicionarServico.setText("Adicionar");
        bntAdicionarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAdicionarServicoActionPerformed(evt);
            }
        });

        bntRemoverServico.setBackground(new java.awt.Color(51, 153, 255));
        bntRemoverServico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntRemoverServico.setForeground(new java.awt.Color(255, 255, 255));
        bntRemoverServico.setText("Remover");
        bntRemoverServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRemoverServicoActionPerformed(evt);
            }
        });

        bntEditarServico.setBackground(new java.awt.Color(51, 153, 255));
        bntEditarServico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntEditarServico.setForeground(new java.awt.Color(255, 255, 255));
        bntEditarServico.setText("Editar");
        bntEditarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEditarServicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bntAdicionarServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bntRemoverServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bntEditarServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblTitulo))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bntAdicionarServico, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntRemoverServico, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(bntEditarServico, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntEditarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEditarServicoActionPerformed
        OrdemServico servicoSelecionado = lstServicos.getSelectedValue();

        if (servicoSelecionado != null) {

            CadastrarOrdemServicoJD telaCadastroServico = new CadastrarOrdemServicoJD(this, true);
            telaCadastroServico.setOrdemServico(servicoSelecionado);

            telaCadastroServico.setVisible(true);

            carregarOrdemServico();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um serviço para editar!!");
        }
    }//GEN-LAST:event_bntEditarServicoActionPerformed

    private void bntAdicionarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAdicionarServicoActionPerformed
        CadastrarOrdemServicoJD telaCadastrarOrdemServico = new CadastrarOrdemServicoJD(this, true);
        telaCadastrarOrdemServico.setDataAberturaHoje();
        telaCadastrarOrdemServico.setVisible(true);

        OrdemServico servicoNovo = telaCadastrarOrdemServico.getOrdemServico();

        OrdemServicoController control = new OrdemServicoController();
        listaOrdemServico = (ArrayList<OrdemServico>) control.addOrdemServico(servicoNovo, listaOrdemServico);
        carregarOrdemServico();
    }//GEN-LAST:event_bntAdicionarServicoActionPerformed

    private void bntRemoverServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRemoverServicoActionPerformed
         OrdemServico servicoSelecionado = lstServicos.getSelectedValue();
        if (servicoSelecionado != null) {
            int opRemover = JOptionPane.showConfirmDialog(rootPane, "Tem certeza que deseja remover o serviço? " + servicoSelecionado.getNome());
            if (opRemover == JOptionPane.YES_OPTION) {
                listaOrdemServico.remove(servicoSelecionado);
                carregarOrdemServico();
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um serviço para remover!!");
        }
    }//GEN-LAST:event_bntRemoverServicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrdemServicoJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrdemServicoJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrdemServicoJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrdemServicoJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrdemServicoJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAdicionarServico;
    private javax.swing.JButton bntEditarServico;
    private javax.swing.JButton bntRemoverServico;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JList<OrdemServico> lstServicos;
    // End of variables declaration//GEN-END:variables
}
